cart/urls.py
from django.contrib import admin
from django.urls import path, include

from cart.views import OrderSummaryView, add_to_cart, remove_from_cart, remove_single_item_from_cart, CheckoutView, \
    StripePaymentView

urlpatterns = [
    path('cart', OrderSummaryView.as_view(), name='cart_page'),
    path('add-to-cart/<slug>', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<slug>', remove_from_cart, name='remove_from_cart'),
    path('remove-single-item/<slug>', remove_single_item_from_cart, name='remove_single_item'),
    path('checkout', CheckoutView.as_view(), name='checkout'),
    path('stripe/', StripePaymentView.as_view(), name='stripe'),
]

delivery/urls.py
from django.contrib import admin
from django.urls import path, include

from delivery.views import HomeView, ProductDetailView
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('detail/<str:slug>', ProductDetailView.as_view(), name='detail'),
]

food_delivery/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('delivery.urls')),
                  path('', include('authorization_system.urls')),
                  path('', include('cart.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delivery/models.py
from django.db import models
from django.urls import reverse
from django_extensions.db.fields import AutoSlugField


class Category(models.Model):
    name = models.CharField('category name', max_length=255, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    description = models.TextField('description', null=True)
    name = models.CharField('product name', max_length=255, null=True)
    product_composition = models.TextField('product composition', null=True)
    price = models.DecimalField('price', decimal_places=2, max_digits=10)
    main_photo = models.ImageField(upload_to='photo/product', null=True)
    category = models.ManyToManyField(Category)
    slug = AutoSlugField(max_length=50, unique=True, populate_from='name')
    discount_price = models.FloatField('discount price', blank=True, null=True)


    def get_absolute_url(self):
        return reverse('detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name


class Photo(models.Model):
    photo = models.ImageField(upload_to='photo/product')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='photo')

delivery/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView, ListView, DetailView

from cart.models import Order
from delivery.models import Product, Category


class HomeView(ListView):
    model = Product
    template_name = '../templates/delivery/home.html'
    context_object_name = 'products'
    paginate_by = 1

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context

    def get_queryset(self):
        qs = self.model.objects.all()
        if self.request.GET.get('category'):
            print(self.request.GET['category'])
            if self.request.GET['category'] == 'all':
                return qs
            return qs.filter(category__name=self.request.GET['category'])
        return qs


class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = '../templates/delivery/detail.html'
    slug_field = 'slug'

templates/delivery/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>{{ product.slug }}</title>
{% endblock %}
{% block content %}

    <div class="container">
        <div>
            <img src="{% static 'img/Fresh-food_thumbnail_1536x1536_200_Standard.jpg' %}" alt="">
        </div>
        <div class="row">
            {% for product_image in product.photo_set.all %}
                <img id="img" src="{{ product_image.photo.url }}">
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/delivery/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Home</title>
{% endblock %}
{% block content %}
    <div class="container ">

        <div>
            <img src="{% static 'img/Fresh-food_thumbnail_1536x1536_200_Standard.jpg' %}" alt="">
        </div>

        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

            <!-- Navbar brand -->
            <span class="navbar-brand">Categories:</span>

            <!-- Collapse button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                    aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Collapsible content -->
            <div class="collapse navbar-collapse" id="basicExampleNav">

                <!-- Links -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a href="/?category=all" class="nav-link">All</a>
                    </li>
                    {% for category in category %}
                        <li class="nav-item">
                            <a class="nav-link"
                               href="?category={{ category }}">{{ category }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
                <!-- Links -->

                <form class="form-inline">
                    <div class="md-form my-0">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    </div>
                </form>
            </div>
            <!-- Collapsible content -->

        </nav>
        <!--/.Navbar-->

        <!--Section: Products v.3-->
        <section class="text-center mb-4">

            <div class="row wow fadeIn">

                {% for product in products.all %}
                    <div class="col-lg-3 col-md-6 mb-4">

                        <div class="card">

                            <div class="view overlay">
                                <img src="{{ product.main_photo.url }}" class="card-img-top" height="200">
                                <a href="{{ product.get_absolute_url }}">
                                    <div class="mask rgba-white-slight"></div>
                                </a>
                            </div>

                            <div class="card-body text-center">
                                <a href="" class="grey-text">
                                    <h5>{{ product.category.first }}</h5>
                                </a>
                                <h5>
                                    <strong>
                                        <a href="{{ product.get_absolute_url }}"
                                           class="dark-grey-text">{{ product.name }}
                                        </a>
                                    </strong>
                                </h5>

                                <h4 class="font-weight-bold blue-text">
                                    <strong>
                                        {{ product.price }} $
                                    </strong>
                                </h4>

                                <a class="btn btn-primary btn-md my-0 p" href="{% url 'add_to_cart' product.slug %}">Add
                                    to cart
                                    <i class="fas fa-shopping-cart ml-1"></i>
                                </a>

                            </div>

                        </div>

                    </div>
                {% endfor %}
            </div>

        </section>

        <!--Pagination-->
        {% if is_paginated %}
            <nav class="d-flex justify-content-center wow fadeIn">
                <ul class="pagination pg-blue">

                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link"
                               href="/?category={{ request.GET.category }}&page={{ page_obj.previous_page_number }}"
                               aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                    {% endif %}

                    <li class="page-item active">
                        <a class="page-link" href="/?category={{ request.GET.category }}&page={{ page_obj.number }}">{{ page_obj.number }}
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="/?category={{ request.GET.category }}&page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>
{% endblock %}