authorization_system/urls.py
from django.urls import path, include

from authorization_system import views
from delivery.views import HomeView

urlpatterns = [
    path('login/', views.AuthView.as_view(), name='login'),
    path('register/', views.RegisterUserView.as_view(), name='register'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
    path('profile/<slug>', views.ProfileView.as_view(), name='profile'),
]

cart/urls.py
from django.contrib import admin
from django.urls import path, include

from cart.views import OrderSummaryView, add_to_cart, remove_from_cart, remove_single_item_from_cart, CheckoutView, \
    StripePaymentView

urlpatterns = [
    path('cart', OrderSummaryView.as_view(), name='cart_page'),
    path('add-to-cart/<slug>', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<slug>', remove_from_cart, name='remove_from_cart'),
    path('remove-single-item/<slug>', remove_single_item_from_cart, name='remove_single_item'),
    path('checkout', CheckoutView.as_view(), name='checkout'),
    path('stripe/', StripePaymentView.as_view(), name='stripe'),
]

food_delivery/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('delivery.urls')),
                  path('', include('authorization_system.urls')),
                  path('', include('cart.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authorization_system/models.py
from django.conf import settings
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django_extensions.db.fields import AutoSlugField


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The Email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self.create_user(username, password, **extra_fields)


class Customer(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField('email address', unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    username = models.CharField('username', max_length=255, null=True, blank=True)
    street_address = models.CharField('street_address', max_length=255, null=True, blank=True)
    apartments_address = models.CharField('apartments_address', max_length=255, null=True, blank=True)
    number = models.CharField('phone number', max_length=255, null=True, blank=True)
    first_name = models.CharField('first name', max_length=255, null=True, blank=True, default='')
    last_name = models.CharField('last name', max_length=255, null=True, blank=True)
    photo = models.ImageField(upload_to='photo/profile_photo', null=True)
    about = models.TextField('about', null=True, blank=True)
    bonuses = models.DecimalField('bonuses', decimal_places=2, max_digits=5, null=True, default=0)
    slug = AutoSlugField(max_length=50, unique=True, populate_from='email')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def get_absolute_url(self):
        return reverse('profile', kwargs={'slug': self.slug})

    def __str__(self):
        return f'{self.first_name or self.email}'

cart/models.py
from django.db import models

from delivery.models import Product
from food_delivery import settings


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.name}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)

    # shipping_address = models.ForeignKey(
    #     'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    # billing_address = models.ForeignKey(
    #     'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    # payment = models.ForeignKey(
    #     'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    # coupon = models.ForeignKey(
    #     'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    # being_delivered = models.BooleanField(default=False)
    # received = models.BooleanField(default=False)
    # refund_requested = models.BooleanField(default=False)
    # refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.email

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        # if self.coupon:
        #     total -= self.coupon.amount
        return total


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    first_name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    number = models.CharField(max_length=255)
    description = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.email

authorization_system/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import Customer


class AuthUserForm(AuthenticationForm):
    class Meta:
        fields = ('password', 'email')


class RegisterUserForm(UserCreationForm):
    class Meta:
        model = Customer
        fields = ('email', 'password1', 'password2')


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('first_name', 'last_name', 'street_address', 'apartments_address', 'number', 'about', 'photo')

authorization_system/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DetailView

from .forms import AuthUserForm, RegisterUserForm, CustomerForm
from .models import Customer
from cart.models import Order


class AuthView(LoginView):
    template_name = 'authorization_system/login.html'
    form_class = AuthUserForm
    success_url = reverse_lazy('home')

    def get_success_url(self):
        return self.success_url


class RegisterUserView(CreateView):
    model = Customer
    template_name = 'authorization_system/register.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form_valid = super().form_valid(form)
        email = form.cleaned_data["email"]
        password = form.cleaned_data["password1"]
        auth_user = authenticate(email=email, password=password)
        login(self.request, auth_user)
        return form_valid


class ProfileView(LoginRequiredMixin, UpdateView):
    login_url = '/login'
    slug_field = 'slug'
    model = Customer
    template_name = 'authorization_system/profile.html'
    context_object_name = 'user'
    form_class = CustomerForm


class LogoutUserView(LogoutView):
    next_page = reverse_lazy('home')

templates/authorization_system/edit_profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}

templates/authorization_system/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}
    <title>Login</title>
{% endblock title %}
{% block content %}
    <form id="add_form" method="post">
        {% csrf_token %}
        <div class="container col-md-5 mt-5">
            {% bootstrap_form form %}
            <button form="add_form" type="submit" class="btn btn-primary mt-5">Login</button>
        </div>
    </form>
{% endblock %}

templates/authorization_system/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block title %}
    <title>Profile</title>
{% endblock title %}
{% block content %}
    <section class="section about-section gray-bg" id="about">
        <div class="container">
            <div class="row align-items-center flex-row-reverse">
                <div class="col-lg-6">
                    <div class="about-text go-to">
                        <div class="row about-list">
                            <div class="col-md-6">
                                <div class="media">
                                    <label>First name</label>
                                    <p>{{ user.first_name }}</p>
                                </div>
                                <div class="media">
                                    <label>Bonuses</label>
                                    <p>{{ user.bonuses }}</p>
                                </div>
                                <div class="media">
                                    <label>Phone</label>
                                    <p>{{ user.number }}</p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="media">
                                    <label>E-mail</label>
                                    <p>{{ user.email }}</p>
                                </div>
                                <div class="media">
                                    <label>Street address</label>
                                    <p>{{ user.street_address }}</p>
                                </div>
                                <div class="media">
                                    <label>Apartments address</label>
                                    <p>{{ user.apartments_address }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="about-avatar">
                        {% if user.photo %}
                            <img src="{{ user.photo.url }}" title="" alt="">
                        {% else %}
                            <img src="https://bootdey.com/img/Content/avatar/avatar7.png" title="" alt="">
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="text-center mt-5">
                    <table class="table table-borderless">
                        <thead>
                        <tr>
                            <th scope="col">№</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            {% for product in user.order_set.all %}
                                {% for foo in product.items.all %}
                                    <td>{{ foo }}</td>
                                {% endfor %}
                            {% endfor %}
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="container">
                <div class="text-center mt-5">
                    <form id="add_form" method="post">
                        {% csrf_token %}
                        <div class="container col-md-5 mt-5">
                            {% bootstrap_form form %}
                            <button form="add_form" type="submit" class="btn btn-primary mt-5">Edit</button>
                        </div>
                    </form>
                </div>
            </div>
    </section>


{% endblock %}

templates/authorization_system/register.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}
    <title>Sign in</title>
{% endblock title %}
{% block content %}
    <form id="add_form" method="post">
        {% csrf_token %}
        <div class="container col-md-5 mt-5">
            {% bootstrap_form form %}
            <button form="add_form" type="submit" class="btn btn-primary mt-5">Sign in</button>
        </div>
    </form>
{% endblock %}